In [2]:
import torch

x=torch.rand(4,3)
print(x)

tensor([[0.0331, 0.9765, 0.7127],
        [0.2953, 0.7282, 0.8688],
        [0.0900, 0.9822, 0.8604],
        [0.4248, 0.5851, 0.5532]])


In [3]:
y=torch.zeros(4,5, dtype=torch.long)
print(y)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])


In [4]:
z=torch.zeros_like(x, dtype=torch.float)
print(z)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [5]:
a=torch.tensor([2.5, 0.1])
print(a)

tensor([2.5000, 0.1000])


In [17]:
x = x.new_ones(4,4)  
print(x)
print(x.size())
print(x.shape)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)
torch.Size([4, 4])
torch.Size([4, 4])


In [18]:
x=torch.eye(4)
print(x)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [19]:
x=torch.arange(0,10,2)
print(x)

tensor([0, 2, 4, 6, 8])


In [21]:
x=torch.linspace(0,10,8)
print(x)

tensor([ 0.0000,  1.4286,  2.8571,  4.2857,  5.7143,  7.1429,  8.5714, 10.0000])


In [23]:
x=torch.rand(5)
print(x)

tensor([0.6582, 0.7255, 0.0118, 0.0952, 0.7226])


In [24]:
x=torch.randn(10)
print(x)

tensor([-0.3378,  1.1282,  0.4961,  1.0015, -0.7838, -0.7777, -0.1568, -0.0942,
         0.2544,  0.7212])


In [30]:
std=torch.arange(1, 0, -0.1)
print(std)
x=torch.normal(mean=1, std=std)
print(x)

tensor([1.0000, 0.9000, 0.8000, 0.7000, 0.6000, 0.5000, 0.4000, 0.3000, 0.2000,
        0.1000])
tensor([-0.5758,  0.1795,  1.4029,  0.6262,  1.0323,  1.4886,  0.9780,  1.1470,
         1.4459,  0.9046])


In [34]:
x=torch.randperm(10)
print(x)

tensor([2, 1, 6, 3, 0, 8, 9, 4, 5, 7])


In [36]:
# tensor add
x=torch.rand(4,3)
y=torch.rand(4,3)
print(x)
print(y)
print(x+y)
print(torch.add(x,y))
print(x.add(y))

tensor([[0.7252, 0.7351, 0.2743],
        [0.7037, 0.7115, 0.0727],
        [0.3006, 0.2249, 0.9396],
        [0.8751, 0.1883, 0.7783]])
tensor([[0.6532, 0.7298, 0.1565],
        [0.5201, 0.4663, 0.7418],
        [0.5052, 0.8447, 0.4936],
        [0.8605, 0.9953, 0.8470]])
tensor([[1.3784, 1.4649, 0.4308],
        [1.2238, 1.1778, 0.8145],
        [0.8058, 1.0696, 1.4332],
        [1.7356, 1.1836, 1.6253]])
tensor([[1.3784, 1.4649, 0.4308],
        [1.2238, 1.1778, 0.8145],
        [0.8058, 1.0696, 1.4332],
        [1.7356, 1.1836, 1.6253]])
tensor([[1.3784, 1.4649, 0.4308],
        [1.2238, 1.1778, 0.8145],
        [0.8058, 1.0696, 1.4332],
        [1.7356, 1.1836, 1.6253]])


In [45]:
#1. 索引操作
x=torch.rand(4,3,dtype=torch.double)
print(x)
second = x[:,2]
print(second)
y = torch.ones(4)
print(y)
second+=y
print(second)
print(x)

tensor([[0.4507, 0.9278, 0.2012],
        [0.0032, 0.3275, 0.2471],
        [0.3097, 0.3136, 0.4683],
        [0.2959, 0.5795, 0.6748]], dtype=torch.float64)
tensor([0.2012, 0.2471, 0.4683, 0.6748], dtype=torch.float64)
tensor([1., 1., 1., 1.])
tensor([1.2012, 1.2471, 1.4683, 1.6748], dtype=torch.float64)
tensor([[0.4507, 0.9278, 1.2012],
        [0.0032, 0.3275, 1.2471],
        [0.3097, 0.3136, 1.4683],
        [0.2959, 0.5795, 1.6748]], dtype=torch.float64)


In [48]:
# 1. 维度变换
x=torch.randn(4,4)
print(x)
y=x.view(16)
z=x.view(-1,2)
zz=x.view(8,2)
print(y)
print(z)
print(zz)

tensor([[ 0.6058,  0.8399, -0.7401,  0.4895],
        [-2.3737, -0.3192, -0.6364,  1.9828],
        [-0.1862, -0.3918,  0.8673,  0.9766],
        [-0.8838, -1.2496, -0.5521, -0.0765]])
tensor([ 0.6058,  0.8399, -0.7401,  0.4895, -2.3737, -0.3192, -0.6364,  1.9828,
        -0.1862, -0.3918,  0.8673,  0.9766, -0.8838, -1.2496, -0.5521, -0.0765])
tensor([[ 0.6058,  0.8399],
        [-0.7401,  0.4895],
        [-2.3737, -0.3192],
        [-0.6364,  1.9828],
        [-0.1862, -0.3918],
        [ 0.8673,  0.9766],
        [-0.8838, -1.2496],
        [-0.5521, -0.0765]])
tensor([[ 0.6058,  0.8399],
        [-0.7401,  0.4895],
        [-2.3737, -0.3192],
        [-0.6364,  1.9828],
        [-0.1862, -0.3918],
        [ 0.8673,  0.9766],
        [-0.8838, -1.2496],
        [-0.5521, -0.0765]])


In [50]:
x=torch.arange(1,3).view(1,2)
y=torch.arange(1,4).view(3,1)
print(x)
print(y)
print(x+y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])
